spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-empty-pine-aoxe4du7.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3OGkJ6CNhdHD
spring.jpa.hibernate.ddl-auto=update